/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei' //, useAnimations

export default function Model(props) {
  const group = useRef()
  const { nodes } = useGLTF('/LandingModel.gltf') // , materials, animations
  // const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Text_First.geometry}
        material={nodes.Text_First.material}
        position={[-0.13, 0.27, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.71}
      />
      <mesh
        geometry={nodes.Text_Aid.geometry}
        material={nodes.Text_Aid.material}
        position={[1.44, -1.01, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.71}
      />
      <mesh
        name="Plane001_cell002"
        geometry={nodes.Plane001_cell002.geometry}
        material={nodes.Plane001_cell002.material}
        position={[-0.53, 0.58, -0.12]}
        rotation={[-3.03, -0.36, -2.88]}
      />
      <mesh
        name="Plane001_cell007"
        geometry={nodes.Plane001_cell007.geometry}
        material={nodes.Plane001_cell007.material}
        position={[0.46, 0.63, -0.11]}
        rotation={[3.1, 0.24, 2.62]}
      />
      <mesh
        name="Plane001_cell008"
        geometry={nodes.Plane001_cell008.geometry}
        material={nodes.Plane001_cell008.material}
        position={[0.51, 0.55, -0.14]}
        rotation={[-0.37, -0.32, 0.79]}
      />
      <mesh
        name="Plane001_cell017"
        geometry={nodes.Plane001_cell017.geometry}
        material={nodes.Plane001_cell017.material}
        position={[0.39, 0.28, -0.14]}
        rotation={[-1.36, -0.07, -1.65]}
        scale={2.46}
      />
      <mesh
        name="Plane001_cell023"
        geometry={nodes.Plane001_cell023.geometry}
        material={nodes.Plane001_cell023.material}
        position={[-0.87, 0.24, -0.11]}
        rotation={[-0.12, 0.15, 2.9]}
      />
      <mesh
        name="Plane001_cell032"
        geometry={nodes.Plane001_cell032.geometry}
        material={nodes.Plane001_cell032.material}
        position={[0.54, 0.08, -0.13]}
        rotation={[-0.17, -0.58, 0.99]}
      />
      <mesh
        name="Plane001_cell040"
        geometry={nodes.Plane001_cell040.geometry}
        material={nodes.Plane001_cell040.material}
        position={[-0.06, -0.12, -0.14]}
        rotation={[3.14, -0.47, -2.7]}
      />
      <mesh
        name="Plane001_cell048"
        geometry={nodes.Plane001_cell048.geometry}
        material={nodes.Plane001_cell048.material}
        position={[-0.88, -0.44, -0.1]}
        rotation={[-0.76, 0.57, -0.36]}
      />
      <mesh
        name="Plane001_cell051"
        geometry={nodes.Plane001_cell051.geometry}
        material={nodes.Plane001_cell051.material}
        position={[-0.25, -0.46, 0.22]}
        rotation={[-0.9, -0.6, -0.22]}
      />
      <mesh
        name="Plane001_cell052"
        geometry={nodes.Plane001_cell052.geometry}
        material={nodes.Plane001_cell052.material}
        position={[0.07, -0.46, 0.14]}
        rotation={[0.56, 0.78, -0.49]}
      />
      <mesh
        name="Plane001_cell054"
        geometry={nodes.Plane001_cell054.geometry}
        material={nodes.Plane001_cell054.material}
        position={[0.69, -0.45, -0.05]}
        rotation={[1.23, -0.11, -0.42]}
      />
      <mesh
        name="Plane001_cell055"
        geometry={nodes.Plane001_cell055.geometry}
        material={nodes.Plane001_cell055.material}
        position={[0.78, -0.39, 0.7]}
        rotation={[-2.5, -0.46, -2.42]}
      />
      <mesh
        name="Plane001_cell056"
        geometry={nodes.Plane001_cell056.geometry}
        material={nodes.Plane001_cell056.material}
        position={[0.98, -0.38, 0.61]}
        rotation={[-2.81, -0.88, -0.88]}
      />
      <mesh
        name="Plane001_cell064"
        geometry={nodes.Plane001_cell064.geometry}
        material={nodes.Plane001_cell064.material}
        position={[-0.14, -0.58, 0.35]}
        rotation={[0.71, -0.44, 0.13]}
      />
      <mesh
        name="Plane001_cell065"
        geometry={nodes.Plane001_cell065.geometry}
        material={nodes.Plane001_cell065.material}
        position={[0.11, -0.54, 0.1]}
        rotation={[-3, -0.85, -0.69]}
      />
      <mesh
        name="Plane001_cell066"
        geometry={nodes.Plane001_cell066.geometry}
        material={nodes.Plane001_cell066.material}
        position={[0.22, -0.75, -0.05]}
        rotation={[0.21, 0.72, -0.91]}
      />
      <mesh
        name="Plane001_cell070"
        geometry={nodes.Plane001_cell070.geometry}
        material={nodes.Plane001_cell070.material}
        position={[0.82, -0.62, -0.19]}
        rotation={[-1.61, 0.36, -0.72]}
      />
      <mesh
        name="Plane001_cell071"
        geometry={nodes.Plane001_cell071.geometry}
        material={nodes.Plane001_cell071.material}
        position={[0.99, -0.62, -0.18]}
        rotation={[-0.4, 0.93, 0.08]}
      />
      <mesh
        name="Plane001_cell072"
        geometry={nodes.Plane001_cell072.geometry}
        material={nodes.Plane001_cell072.material}
        position={[-0.9, -0.9, 1.85]}
        rotation={[-0.01, 0.71, -0.07]}
        scale={[1.29, 1.29, 1.29]}
      />
      <mesh
        name="Plane001_cell077"
        geometry={nodes.Plane001_cell077.geometry}
        material={nodes.Plane001_cell077.material}
        position={[-0.08, -0.84, 0.1]}
        rotation={[0.28, 0.4, -0.25]}
      />
      <mesh
        name="Plane001_cell094"
        geometry={nodes.Plane001_cell094.geometry}
        material={nodes.Plane001_cell094.material}
        position={[-0.41, -1.11, 0.13]}
        rotation={[-0.68, 0.77, 0.12]}
      />
      <mesh
        name="Plane001_cell095"
        geometry={nodes.Plane001_cell095.geometry}
        material={nodes.Plane001_cell095.material}
        position={[-0.25, -0.91, 0.1]}
        rotation={[2.95, -0.79, 0.94]}
      />
      <mesh
        name="Plane001_cell096"
        geometry={nodes.Plane001_cell096.geometry}
        material={nodes.Plane001_cell096.material}
        position={[-0.01, -1.2, 0.62]}
        rotation={[-1.98, 1.06, 1.89]}
        scale={[2.19, 2.19, 2.19]}
      />
      <mesh
        name="Plane001_cell100"
        geometry={nodes.Plane001_cell100.geometry}
        material={nodes.Plane001_cell100.material}
        position={[0.7, -1.14, -0.15]}
        rotation={[0.15, -0.5, 0.32]}
      />
      <mesh
        name="Plane001_cell104"
        geometry={nodes.Plane001_cell104.geometry}
        material={nodes.Plane001_cell104.material}
        position={[-0.46, -1.33, 0.23]}
        rotation={[1.21, 0.17, -0.55]}
      />
      <mesh
        name="Plane001_cell105"
        geometry={nodes.Plane001_cell105.geometry}
        material={nodes.Plane001_cell105.material}
        position={[0.29, -1.3, -0.16]}
        rotation={[-0.31, 0.23, 0.07]}
      />
      <mesh
        name="Plane001_cell106"
        geometry={nodes.Plane001_cell106.geometry}
        material={nodes.Plane001_cell106.material}
        position={[0.72, -1.4, -0.15]}
        rotation={[-2.92, -0.54, -0.51]}
      />
      <mesh
        name="Plane001_cell107"
        geometry={nodes.Plane001_cell107.geometry}
        material={nodes.Plane001_cell107.material}
        position={[0.24, 0.46, -0.16]}
        rotation={[-0.04, -0.16, 0.09]}
      />
      <mesh
        name="Plane002_cell634"
        geometry={nodes.Plane002_cell634.geometry}
        material={nodes.Plane002_cell634.material}
        position={[-1.75, 0.27, 0.72]}
        rotation={[-2.87, -0.57, -1.58]}
      />
      <mesh
        name="Plane002_cell636"
        geometry={nodes.Plane002_cell636.geometry}
        material={nodes.Plane002_cell636.material}
        position={[-3.03, -0.85, 0.62]}
        rotation={[0.87, 0.3, 2.52]}
      />
      <mesh
        name="Plane002_cell637"
        geometry={nodes.Plane002_cell637.geometry}
        material={nodes.Plane002_cell637.material}
        position={[-2.95, -0.54, 0.77]}
        rotation={[1.18, 0.77, 1.4]}
      />
      <mesh
        name="Plane002_cell639"
        geometry={nodes.Plane002_cell639.geometry}
        material={nodes.Plane002_cell639.material}
        position={[-2.87, 0.34, 0.78]}
        rotation={[0.84, 0.63, 2.77]}
        scale={[2.06, 2.06, 2.06]}
      />
      <mesh
        name="Plane002_cell640"
        geometry={nodes.Plane002_cell640.geometry}
        material={nodes.Plane002_cell640.material}
        position={[-2.86, -1.29, 0.73]}
        rotation={[1.7, 1.32, -1.27]}
      />
      <mesh
        name="Plane002_cell642"
        geometry={nodes.Plane002_cell642.geometry}
        material={nodes.Plane002_cell642.material}
        position={[-2.78, -0.91, 0.85]}
        rotation={[-0.7, 0.25, 2.61]}
        scale={1.64}
      />
      <mesh
        name="Plane002_cell644"
        geometry={nodes.Plane002_cell644.geometry}
        material={nodes.Plane002_cell644.material}
        position={[-2.78, -0.59, 0.59]}
        rotation={[0.26, -1.24, -2.28]}
      />
      <mesh
        name="Plane002_cell646"
        geometry={nodes.Plane002_cell646.geometry}
        material={nodes.Plane002_cell646.material}
        position={[-2.75, -0.21, 0.54]}
        rotation={[-1.45, -0.91, -2.35]}
      />
      <mesh
        name="Plane002_cell650"
        geometry={nodes.Plane002_cell650.geometry}
        material={nodes.Plane002_cell650.material}
        position={[-2.68, 0.46, 0.63]}
        rotation={[-0.6, 0.86, -1.42]}
        scale={[1.49, 1.49, 1.49]}
      />
      <mesh
        name="Plane002_cell656"
        geometry={nodes.Plane002_cell656.geometry}
        material={nodes.Plane002_cell656.material}
        position={[-2.42, -0.27, 1]}
        rotation={[-1.61, 0.36, -0.72]}
      />
      <mesh
        name="Plane002_cell658"
        geometry={nodes.Plane002_cell658.geometry}
        material={nodes.Plane002_cell658.material}
        position={[-2.38, 0.19, 0.64]}
        rotation={[2.76, -0.42, -1.54]}
        scale={[2.14, 2.14, 2.14]}
      />
      <mesh
        name="Plane002_cell660"
        geometry={nodes.Plane002_cell660.geometry}
        material={nodes.Plane002_cell660.material}
        position={[-2.48, 0.53, 0.7]}
        rotation={[2.82, 0.56, 1.62]}
      />
      <mesh
        name="Plane002_cell661"
        geometry={nodes.Plane002_cell661.geometry}
        material={nodes.Plane002_cell661.material}
        position={[-2.51, 0.69, 0.6]}
        rotation={[1.81, -0.07, -2.31]}
      />
      <mesh
        name="Plane002_cell674"
        geometry={nodes.Plane002_cell674.geometry}
        material={nodes.Plane002_cell674.material}
        position={[-2.25, 0.56, 0.59]}
        rotation={[-1.11, 0.24, -1.38]}
      />
      <mesh
        name="Plane002_cell683"
        geometry={nodes.Plane002_cell683.geometry}
        material={nodes.Plane002_cell683.material}
        position={[-1.89, 0.07, 1.2]}
        rotation={[-0.9, 0.73, 1.13]}
        scale={[3.1, 3.1, 3.1]}
      />
      <mesh
        name="Plane002_cell685"
        geometry={nodes.Plane002_cell685.geometry}
        material={nodes.Plane002_cell685.material}
        position={[-1.92, 0.61, 0.79]}
        rotation={[-2.18, 0.25, -1.21]}
      />
      <mesh
        name="Plane002_cell690"
        geometry={nodes.Plane002_cell690.geometry}
        material={nodes.Plane002_cell690.material}
        position={[-0.03, 2.06, -0.01]}
      />
      <mesh
        name="Plane002_cell692"
        geometry={nodes.Plane002_cell692.geometry}
        material={nodes.Plane002_cell692.material}
        position={[-1.82, -0.2, 0.48]}
        rotation={[-1.96, 0.28, -1.04]}
      />
      <mesh
        name="Plane002_cell693"
        geometry={nodes.Plane002_cell693.geometry}
        material={nodes.Plane002_cell693.material}
        position={[-1.65, -0.03, 0.8]}
        rotation={[0.16, -0.41, -2.07]}
      />
      <mesh
        name="Plane002_cell696"
        geometry={nodes.Plane002_cell696.geometry}
        material={nodes.Plane002_cell696.material}
        position={[-1.56, 0.52, 1.12]}
        rotation={[1.49, -1.06, 0.36]}
      />
      <mesh
        name="Plane002_cell697"
        geometry={nodes.Plane002_cell697.geometry}
        material={nodes.Plane002_cell697.material}
        position={[-1.64, 0.88, 0.62]}
        rotation={[-2.21, -0.02, 1.01]}
      />
      <mesh
        name="Plane002_cell708"
        geometry={nodes.Plane002_cell708.geometry}
        material={nodes.Plane002_cell708.material}
        position={[-1.65, 0.33, 0.07]}
        rotation={[-1.35, -0.86, 1.48]}
      />
      <mesh
        name="Plane002_cell710"
        geometry={nodes.Plane002_cell710.geometry}
        material={nodes.Plane002_cell710.material}
        position={[-1.36, 0.84, -0.06]}
        rotation={[-2.25, 0.3, 0.65]}
      />
      <mesh
        name="Plane002_cell717"
        geometry={nodes.Plane002_cell717.geometry}
        material={nodes.Plane002_cell717.material}
        position={[-1.26, -0.76, 0.31]}
        rotation={[-2.45, 0.27, -0.28]}
      />
      <mesh
        name="Plane002_cell719"
        geometry={nodes.Plane002_cell719.geometry}
        material={nodes.Plane002_cell719.material}
        position={[-1.15, -0.22, -0.18]}
        rotation={[2.74, -0.73, -1.53]}
      />
      <mesh
        name="Plane002_cell724"
        geometry={nodes.Plane002_cell724.geometry}
        material={nodes.Plane002_cell724.material}
        position={[-1.32, -0.92, 0.58]}
        rotation={[2.79, 0.91, 0.45]}
      />
      <mesh
        name="Plane002_cell725"
        geometry={nodes.Plane002_cell725.geometry}
        material={nodes.Plane002_cell725.material}
        position={[-1.2, -0.79, 0.73]}
        rotation={[-0.15, -0.25, -1.98]}
      />
      <mesh
        name="Plane002_cell726"
        geometry={nodes.Plane002_cell726.geometry}
        material={nodes.Plane002_cell726.material}
        position={[-1.15, -0.65, 0.74]}
        rotation={[-0.62, -0.12, -1.85]}
      />
      <mesh
        name="Plane004_cell733"
        geometry={nodes.Plane004_cell733.geometry}
        material={nodes.Plane004_cell733.material}
        position={[1.26, -1.12, -0.13]}
        rotation={[0.14, 0.79, -0.03]}
      />
      <mesh
        name="Plane004_cell735"
        geometry={nodes.Plane004_cell735.geometry}
        material={nodes.Plane004_cell735.material}
        position={[1.38, -0.3, 0.18]}
        rotation={[2.2, 0.54, 1.47]}
        scale={[1.44, 1.44, 1.44]}
      />
      <mesh
        name="Plane004_cell737"
        geometry={nodes.Plane004_cell737.geometry}
        material={nodes.Plane004_cell737.material}
        position={[1.29, -0.06, 0.6]}
        rotation={[-1.14, -0.3, 1.32]}
      />
      <mesh
        name="Plane004_cell738"
        geometry={nodes.Plane004_cell738.geometry}
        material={nodes.Plane004_cell738.material}
        position={[1.28, 0.18, 0.84]}
        rotation={[-0.33, -0.85, -3.11]}
      />
      <mesh
        name="Plane004_cell739"
        geometry={nodes.Plane004_cell739.geometry}
        material={nodes.Plane004_cell739.material}
        position={[1.25, 0.5, 0.06]}
        rotation={[-0.36, 1.03, -0.54]}
      />
      <mesh
        name="Plane004_cell747"
        geometry={nodes.Plane004_cell747.geometry}
        material={nodes.Plane004_cell747.material}
        position={[1.18, 0.1, 0.69]}
        rotation={[0.64, 0.71, 2.59]}
      />
      <mesh
        name="Plane004_cell749"
        geometry={nodes.Plane004_cell749.geometry}
        material={nodes.Plane004_cell749.material}
        position={[1.35, 0.19, -0.32]}
        rotation={[2, 0.55, -0.7]}
      />
      <mesh
        name="Plane004_cell750"
        geometry={nodes.Plane004_cell750.geometry}
        material={nodes.Plane004_cell750.material}
        position={[1.58, 0.24, -0.42]}
        rotation={[1.25, 0.16, 1.45]}
      />
      <mesh
        name="Plane004_cell751"
        geometry={nodes.Plane004_cell751.geometry}
        material={nodes.Plane004_cell751.material}
        position={[1.02, 0.29, -0.52]}
        rotation={[-1.25, 0.85, -0.08]}
      />
      <mesh
        name="Plane004_cell752"
        geometry={nodes.Plane004_cell752.geometry}
        material={nodes.Plane004_cell752.material}
        position={[1.58, 0.58, 0.76]}
        rotation={[-2.92, 0.82, 2.4]}
      />
      <mesh
        name="Plane004_cell753"
        geometry={nodes.Plane004_cell753.geometry}
        material={nodes.Plane004_cell753.material}
        position={[1.46, -1.41, -0.14]}
        rotation={[-2.69, -0.25, -0.16]}
      />
      <mesh
        name="Plane004_cell754"
        geometry={nodes.Plane004_cell754.geometry}
        material={nodes.Plane004_cell754.material}
        position={[1.68, -1.26, -0.23]}
        rotation={[-1.38, 0.7, -2.31]}
      />
      <mesh
        name="Plane004_cell755"
        geometry={nodes.Plane004_cell755.geometry}
        material={nodes.Plane004_cell755.material}
        position={[1.76, -1.1, 0.01]}
        rotation={[-1.15, 0.02, -2.03]}
      />
      <mesh
        name="Plane004_cell758"
        geometry={nodes.Plane004_cell758.geometry}
        material={nodes.Plane004_cell758.material}
        position={[1.79, -0.45, 0.81]}
        rotation={[1.56, -1.1, -0.17]}
      />
      <mesh
        name="Plane004_cell759"
        geometry={nodes.Plane004_cell759.geometry}
        material={nodes.Plane004_cell759.material}
        position={[1.73, -0.29, 1.02]}
        rotation={[1.4, 0.69, 1.21]}
      />
      <mesh
        name="Plane004_cell760"
        geometry={nodes.Plane004_cell760.geometry}
        material={nodes.Plane004_cell760.material}
        position={[2.03, -0.53, -0.33]}
        rotation={[3.01, -0.03, 1.31]}
      />
      <mesh
        name="Plane004_cell761"
        geometry={nodes.Plane004_cell761.geometry}
        material={nodes.Plane004_cell761.material}
        position={[1.56, 0.19, -0.38]}
        rotation={[-1.92, -0.27, -1.41]}
      />
      <mesh
        name="Plane004_cell762"
        geometry={nodes.Plane004_cell762.geometry}
        material={nodes.Plane004_cell762.material}
        position={[1.77, 0.84, -0.72]}
        rotation={[-2.32, 0.09, 1.3]}
      />
      <mesh
        geometry={nodes.Plane004_cell763.geometry}
        material={nodes.Plane004_cell763.material}
        position={[1.87, 0.28, -0.24]}
        rotation={[-2.22, -0.23, 2.04]}
        scale={[4.19, 4.19, 4.19]}
      />
      <mesh
        name="Plane004_cell766"
        geometry={nodes.Plane004_cell766.geometry}
        material={nodes.Plane004_cell766.material}
        position={[1.75, -1.56, 0.73]}
        rotation={[-2.8, 0.69, 0.22]}
      />
      <mesh
        name="Plane004_cell768"
        geometry={nodes.Plane004_cell768.geometry}
        material={nodes.Plane004_cell768.material}
        position={[1.88, -0.98, 0.91]}
        rotation={[-3.06, -0.31, -0.18]}
      />
      <mesh
        name="Plane004_cell770"
        geometry={nodes.Plane004_cell770.geometry}
        material={nodes.Plane004_cell770.material}
        position={[1.83, -0.62, 0.89]}
        rotation={[0.51, 0, 1.49]}
      />
      <mesh
        name="Plane004_cell775"
        geometry={nodes.Plane004_cell775.geometry}
        material={nodes.Plane004_cell775.material}
        position={[2.29, 0.75, -0.45]}
        rotation={[-2.63, 0.26, 2.49]}
        scale={[2.55, 2.55, 2.55]}
      />
      <mesh
        name="Plane004_cell779"
        geometry={nodes.Plane004_cell779.geometry}
        material={nodes.Plane004_cell779.material}
        position={[2.17, -0.98, 0.94]}
        rotation={[-2.63, -1.12, -1.35]}
      />
      <mesh
        name="Plane004_cell780"
        geometry={nodes.Plane004_cell780.geometry}
        material={nodes.Plane004_cell780.material}
        position={[2.05, -0.66, 0.9]}
        rotation={[-1.04, 0.99, 2.22]}
        scale={2.62}
      />
      <mesh
        name="Plane004_cell783"
        geometry={nodes.Plane004_cell783.geometry}
        material={nodes.Plane004_cell783.material}
        position={[2.38, 0.06, 0.42]}
        rotation={[-2.81, 0.21, 1.6]}
      />
      <mesh
        name="Plane004_cell784"
        geometry={nodes.Plane004_cell784.geometry}
        material={nodes.Plane004_cell784.material}
        position={[2.57, 0.58, -0.47]}
        rotation={[-0.28, -0.87, -1.92]}
      />
      <mesh
        name="Plane004_cell785"
        geometry={nodes.Plane004_cell785.geometry}
        material={nodes.Plane004_cell785.material}
        position={[2.24, -0.17, -0.7]}
        rotation={[-1.21, 0.57, -0.88]}
      />
      <mesh
        name="Plane004_cell789"
        geometry={nodes.Plane004_cell789.geometry}
        material={nodes.Plane004_cell789.material}
        position={[2.39, -1.14, 0.61]}
        rotation={[-2.9, 0.12, 1.3]}
      />
      <mesh
        name="Plane004_cell796"
        geometry={nodes.Plane004_cell796.geometry}
        material={nodes.Plane004_cell796.material}
        position={[2.52, -0.17, 1.21]}
        rotation={[-0.32, -0.64, 0.47]}
        scale={[1.34, 1.34, 1.34]}
      />
      <mesh
        name="Plane004_cell800"
        geometry={nodes.Plane004_cell800.geometry}
        material={nodes.Plane004_cell800.material}
        position={[2.47, 0.81, 0.19]}
        rotation={[-2.21, 0.91, 1.45]}
      />
      <mesh
        name="Plane004_cell802"
        geometry={nodes.Plane004_cell802.geometry}
        material={nodes.Plane004_cell802.material}
        position={[2.51, -1.44, 0.68]}
        rotation={[-2.93, -0.11, 0.06]}
      />
      <mesh
        name="Plane004_cell804"
        geometry={nodes.Plane004_cell804.geometry}
        material={nodes.Plane004_cell804.material}
        position={[2.61, -0.97, 0.59]}
        rotation={[-2.41, -0.28, 1.26]}
      />
      <mesh
        name="Plane004_cell806"
        geometry={nodes.Plane004_cell806.geometry}
        material={nodes.Plane004_cell806.material}
        position={[2.57, -0.6, 0.68]}
        rotation={[0.19, -1.09, 1.81]}
      />
      <mesh
        name="Plane004_cell812"
        geometry={nodes.Plane004_cell812.geometry}
        material={nodes.Plane004_cell812.material}
        position={[2.89, -1.25, 0.73]}
        rotation={[3.07, 0.33, 1.45]}
        scale={[1.46, 1.46, 1.46]}
      />
      <mesh
        name="Plane004_cell814"
        geometry={nodes.Plane004_cell814.geometry}
        material={nodes.Plane004_cell814.material}
        position={[2.86, -0.85, 0.82]}
        rotation={[1.39, -0.41, -1.94]}
      />
      <mesh
        name="Plane004_cell817"
        geometry={nodes.Plane004_cell817.geometry}
        material={nodes.Plane004_cell817.material}
        position={[2.96, -0.44, 0.79]}
        rotation={[1.36, -0.58, 2.02]}
      />
      <mesh
        name="Plane004_cell818"
        geometry={nodes.Plane004_cell818.geometry}
        material={nodes.Plane004_cell818.material}
        position={[2.87, -0.14, 0.74]}
        rotation={[-2.48, 0.35, 0.89]}
      />
      <mesh
        name="Plane004_cell820"
        geometry={nodes.Plane004_cell820.geometry}
        material={nodes.Plane004_cell820.material}
        position={[2.93, 0.17, 0.81]}
        rotation={[-0.56, -0.11, 1.07]}
      />
      <mesh
        name="Plane004_cell822"
        geometry={nodes.Plane004_cell822.geometry}
        material={nodes.Plane004_cell822.material}
        position={[3.06, 0.49, 0.88]}
        rotation={[-3.08, 0.77, 1.9]}
      />
      <mesh
        name="Plane004_cell823"
        geometry={nodes.Plane004_cell823.geometry}
        material={nodes.Plane004_cell823.material}
        position={[2.86, 0.61, 0.72]}
        rotation={[-2.43, -1.19, -0.73]}
      />
      <mesh
        name="Plane004_cell827"
        geometry={nodes.Plane004_cell827.geometry}
        material={nodes.Plane004_cell827.material}
        position={[3.23, 0.31, 0.72]}
        rotation={[-0.03, 1.19, -2.93]}
      />
      <mesh
        name="Plane004_cell829"
        geometry={nodes.Plane004_cell829.geometry}
        material={nodes.Plane004_cell829.material}
        position={[1.99, -0.85, 0.71]}
        rotation={[-1.57, 1.19, 3.09]}
      />
      <mesh
        name="Plane003_cell001"
        geometry={nodes.Plane003_cell001.geometry}
        material={nodes.Plane003_cell001.material}
        position={[0.89, 2.17, -1.46]}
        rotation={[-1.22, 0.7, 2.06]}
      />
      <mesh
        name="Plane003_cell005"
        geometry={nodes.Plane003_cell005.geometry}
        material={nodes.Plane003_cell005.material}
        position={[1.21, 2.3, 0.73]}
        rotation={[-1.02, 0.84, -2.24]}
      />
      <mesh
        name="Plane003_cell006"
        geometry={nodes.Plane003_cell006.geometry}
        material={nodes.Plane003_cell006.material}
        position={[1.14, 1.81, 0.41]}
        rotation={[1.26, -0.83, 2.43]}
      />
      <mesh
        name="Plane003_cell009"
        geometry={nodes.Plane003_cell009.geometry}
        material={nodes.Plane003_cell009.material}
        position={[0.96, 2.41, -0.64]}
        rotation={[-2.34, 0.57, -0.86]}
      />
      <mesh
        name="Plane003_cell010"
        geometry={nodes.Plane003_cell010.geometry}
        material={nodes.Plane003_cell010.material}
        position={[1.13, 2.59, -0.51]}
        rotation={[-1.15, 0.19, 2.72]}
      />
      <mesh
        name="Plane003_cell011"
        geometry={nodes.Plane003_cell011.geometry}
        material={nodes.Plane003_cell011.material}
        position={[0.27, 2.24, -0.57]}
        rotation={[-0.44, -0.21, -3.09]}
      />
      <mesh
        name="Plane003_cell012"
        geometry={nodes.Plane003_cell012.geometry}
        material={nodes.Plane003_cell012.material}
        position={[1.08, 2.06, -1.03]}
        rotation={[0.83, 0.8, -1.37]}
        scale={1.03}
      />
      <mesh
        name="Plane003_cell013"
        geometry={nodes.Plane003_cell013.geometry}
        material={nodes.Plane003_cell013.material}
        position={[0.98, 1.99, -1.17]}
        rotation={[2.88, 0.42, 0.37]}
      />
      <mesh
        name="Plane003_cell014"
        geometry={nodes.Plane003_cell014.geometry}
        material={nodes.Plane003_cell014.material}
        position={[0.93, 1.87, -0.56]}
        rotation={[0.95, -0.05, -3.08]}
      />
      <mesh
        name="Plane003_cell019"
        geometry={nodes.Plane003_cell019.geometry}
        material={nodes.Plane003_cell019.material}
        position={[0.97, 0.88, 0.68]}
        rotation={[1.13, -1.16, 2.35]}
      />
      <mesh
        name="Plane003_cell024"
        geometry={nodes.Plane003_cell024.geometry}
        material={nodes.Plane003_cell024.material}
        position={[0.68, 1.87, -0.68]}
        rotation={[2.03, -0.92, 2.76]}
      />
      <mesh
        name="Plane003_cell029"
        geometry={nodes.Plane003_cell029.geometry}
        material={nodes.Plane003_cell029.material}
        position={[0.63, 0.95, 0.61]}
        rotation={[1.5, -1.14, 2.64]}
      />
      <mesh
        name="Plane003_cell037"
        geometry={nodes.Plane003_cell037.geometry}
        material={nodes.Plane003_cell037.material}
        position={[0.37, 1.83, -1.02]}
        rotation={[-0.53, 0.42, -0.9]}
      />
      <mesh
        name="Plane003_cell038"
        geometry={nodes.Plane003_cell038.geometry}
        material={nodes.Plane003_cell038.material}
        position={[0.38, 1.46, 0.59]}
        rotation={[1.96, -0.73, 2.31]}
      />
      <mesh
        name="Plane003_cell039"
        geometry={nodes.Plane003_cell039.geometry}
        material={nodes.Plane003_cell039.material}
        position={[0.38, 1.29, 1.15]}
        rotation={[-0.39, -0.09, 1.58]}
      />
      <mesh
        name="Plane003_cell041"
        geometry={nodes.Plane003_cell041.geometry}
        material={nodes.Plane003_cell041.material}
        position={[0.37, 0.99, 1.06]}
        rotation={[1.97, 0.02, 0.74]}
      />
      <mesh
        name="Plane003_cell051"
        geometry={nodes.Plane003_cell051.geometry}
        material={nodes.Plane003_cell051.material}
        position={[0.19, 1.35, 0.75]}
        rotation={[-2.81, 0.2, 1.3]}
      />
      <mesh
        name="Plane003_cell052"
        geometry={nodes.Plane003_cell052.geometry}
        material={nodes.Plane003_cell052.material}
        position={[0.03, 1.32, 1.01]}
        rotation={[1.42, 0.13, -2.35]}
      />
      <mesh
        name="Plane003_cell060"
        geometry={nodes.Plane003_cell060.geometry}
        material={nodes.Plane003_cell060.material}
        position={[-0.15, 1.58, 0.1]}
        rotation={[1.76, 0.82, 0.19]}
      />
      <mesh
        name="Plane003_cell062"
        geometry={nodes.Plane003_cell062.geometry}
        material={nodes.Plane003_cell062.material}
        position={[-0.12, 1.24, 0.44]}
        rotation={[-2.85, 0.77, 0.46]}
      />
      <mesh
        name="Plane003_cell063"
        geometry={nodes.Plane003_cell063.geometry}
        material={nodes.Plane003_cell063.material}
        position={[-0.1, 1.21, 0.68]}
        rotation={[-3.01, -0.79, 2.34]}
      />
      <mesh
        name="Plane003_cell065"
        geometry={nodes.Plane003_cell065.geometry}
        material={nodes.Plane003_cell065.material}
        position={[-0.22, 0.91, 0.74]}
        rotation={[1.12, -0.49, 1.21]}
      />
      <mesh
        name="Plane003_cell074"
        geometry={nodes.Plane003_cell074.geometry}
        material={nodes.Plane003_cell074.material}
        position={[-0.28, 1.74, 0.39]}
        rotation={[2.65, 0.17, -2.19]}
      />
      <mesh
        name="Plane003_cell079"
        geometry={nodes.Plane003_cell079.geometry}
        material={nodes.Plane003_cell079.material}
        position={[-0.5, 0.7, -0.23]}
        rotation={[0.22, 0.81, -2.44]}
      />
      <mesh
        name="Plane003_cell080"
        geometry={nodes.Plane003_cell080.geometry}
        material={nodes.Plane003_cell080.material}
        position={[-0.52, 2.57, -1.17]}
        rotation={[-0.29, -0.04, -0.12]}
      />
      <mesh
        name="Plane003_cell081"
        geometry={nodes.Plane003_cell081.geometry}
        material={nodes.Plane003_cell081.material}
        position={[-0.55, 2.34, -1.13]}
        rotation={[2.34, 1.01, 2.24]}
      />
      <mesh
        name="Plane003_cell082"
        geometry={nodes.Plane003_cell082.geometry}
        material={nodes.Plane003_cell082.material}
        position={[-0.31, 2.2, -1.21]}
        rotation={[2.35, 0.49, 2.35]}
      />
      <mesh
        name="Plane003_cell087"
        geometry={nodes.Plane003_cell087.geometry}
        material={nodes.Plane003_cell087.material}
        position={[-0.54, 1.69, 0.38]}
        rotation={[-3.13, 0.06, 1.76]}
      />
      <mesh
        name="Plane003_cell088"
        geometry={nodes.Plane003_cell088.geometry}
        material={nodes.Plane003_cell088.material}
        position={[-0.58, 1.04, 0.79]}
        rotation={[-0.26, -0.6, 1.38]}
        scale={[1.32, 1.32, 1.32]}
      />
      <mesh
        name="Plane003_cell089"
        geometry={nodes.Plane003_cell089.geometry}
        material={nodes.Plane003_cell089.material}
        position={[-1.12, 0.73, -0.24]}
        rotation={[-0.62, 0.44, 2.36]}
        scale={[2.41, 2.41, 2.41]}
      />
      <mesh
        name="Plane003_cell090"
        geometry={nodes.Plane003_cell090.geometry}
        material={nodes.Plane003_cell090.material}
        position={[-0.57, 1.05, 0.52]}
        rotation={[2.62, -0.39, 1.29]}
      />
      <mesh
        name="Plane003_cell092"
        geometry={nodes.Plane003_cell092.geometry}
        material={nodes.Plane003_cell092.material}
        position={[-0.61, 2.57, -0.98]}
        rotation={[-1.27, -0.43, 1.09]}
      />
      <mesh
        name="Plane003_cell094"
        geometry={nodes.Plane003_cell094.geometry}
        material={nodes.Plane003_cell094.material}
        position={[-0.86, 2.18, -1.04]}
        rotation={[-1.41, 0.08, -0.16]}
      />
      <mesh
        name="Plane003_cell095"
        geometry={nodes.Plane003_cell095.geometry}
        material={nodes.Plane003_cell095.material}
        position={[-0.85, 1.96, -1.4]}
        rotation={[-2.24, -0.02, 0.5]}
      />
      <mesh
        name="Plane003_cell098"
        geometry={nodes.Plane003_cell098.geometry}
        material={nodes.Plane003_cell098.material}
        position={[-0.99, 1.18, 0.82]}
        rotation={[2.99, -0.69, 0.57]}
      />
      <mesh
        name="Plane003_cell099"
        geometry={nodes.Plane003_cell099.geometry}
        material={nodes.Plane003_cell099.material}
        position={[-0.84, 1.06, 0.83]}
        rotation={[0.85, -0.08, 0.85]}
      />
      <mesh
        name="Plane005_cell016"
        geometry={nodes.Plane005_cell016.geometry}
        material={nodes.Plane005_cell016.material}
        position={[1.01, -1.69, -0.28]}
        rotation={[-2.51, -0.72, -0.45]}
      />
      <mesh
        name="Plane005_cell017"
        geometry={nodes.Plane005_cell017.geometry}
        material={nodes.Plane005_cell017.material}
        position={[1.04, -1.62, 0.82]}
        rotation={[1.91, -0.37, -0.76]}
      />
      <mesh
        name="Plane005_cell020"
        geometry={nodes.Plane005_cell020.geometry}
        material={nodes.Plane005_cell020.material}
        position={[0.95, -1.77, 0.84]}
        rotation={[-1.93, -0.43, -2.4]}
      />
      <mesh
        name="Plane005_cell021"
        geometry={nodes.Plane005_cell021.geometry}
        material={nodes.Plane005_cell021.material}
        position={[0.92, -2.13, 1.04]}
        rotation={[2.7, -0.21, 1.89]}
        scale={[1.68, 1.68, 1.68]}
      />
      <mesh
        name="Plane005_cell033"
        geometry={nodes.Plane005_cell033.geometry}
        material={nodes.Plane005_cell033.material}
        position={[1, -3.29, 0.6]}
        rotation={[1.48, -0.59, -2.36]}
      />
      <mesh
        name="Plane005_cell036"
        geometry={nodes.Plane005_cell036.geometry}
        material={nodes.Plane005_cell036.material}
        position={[1.02, -1.58, -0.07]}
        rotation={[-1.57, 0.87, -2.46]}
      />
      <mesh
        name="Plane005_cell037"
        geometry={nodes.Plane005_cell037.geometry}
        material={nodes.Plane005_cell037.material}
        position={[0.78, -1.83, 0.34]}
        rotation={[-1.69, -0.76, 0.78]}
      />
      <mesh
        name="Plane005_cell040"
        geometry={nodes.Plane005_cell040.geometry}
        material={nodes.Plane005_cell040.material}
        position={[0.67, -2.19, 0.63]}
        rotation={[-2.37, -0.83, -0.71]}
      />
      <mesh
        name="Plane005_cell056"
        geometry={nodes.Plane005_cell056.geometry}
        material={nodes.Plane005_cell056.material}
        position={[0.72, -3.04, 0.71]}
        rotation={[2.43, 0.95, 0.32]}
      />
      <mesh
        name="Plane005_cell057"
        geometry={nodes.Plane005_cell057.geometry}
        material={nodes.Plane005_cell057.material}
        position={[0.78, -3.17, 0.98]}
        rotation={[-2.41, 0.02, 2.86]}
      />
      <mesh
        name="Plane005_cell061"
        geometry={nodes.Plane005_cell061.geometry}
        material={nodes.Plane005_cell061.material}
        position={[0.85, -1.43, -0.13]}
        rotation={[-2.78, 1.05, 2.94]}
      />
      <mesh
        name="Plane005_cell063"
        geometry={nodes.Plane005_cell063.geometry}
        material={nodes.Plane005_cell063.material}
        position={[0.76, -1.51, -0.2]}
        rotation={[3.12, 1.1, 1.61]}
      />
      <mesh
        name="Plane005_cell065"
        geometry={nodes.Plane005_cell065.geometry}
        material={nodes.Plane005_cell065.material}
        position={[0.38, -1.59, -0.24]}
        rotation={[2.42, -0.9, -0.59]}
      />
      <mesh
        name="Plane005_cell068"
        geometry={nodes.Plane005_cell068.geometry}
        material={nodes.Plane005_cell068.material}
        position={[0.43, -2.14, 0.98]}
        rotation={[2.51, 1.24, 2.28]}
      />
      <mesh
        name="Plane005_cell069"
        geometry={nodes.Plane005_cell069.geometry}
        material={nodes.Plane005_cell069.material}
        position={[0.44, -2.38, 1.02]}
        rotation={[-0.9, -0.5, -2.01]}
      />
      <mesh
        name="Plane005_cell084"
        geometry={nodes.Plane005_cell084.geometry}
        material={nodes.Plane005_cell084.material}
        position={[0.52, -3.05, 0.64]}
        rotation={[0.75, 0.36, -0.68]}
      />
      <mesh
        name="Plane005_cell086"
        geometry={nodes.Plane005_cell086.geometry}
        material={nodes.Plane005_cell086.material}
        position={[0.42, -1.42, -0.16]}
        rotation={[-2.36, 0.05, -1.83]}
      />
      <mesh
        name="Plane005_cell089"
        geometry={nodes.Plane005_cell089.geometry}
        material={nodes.Plane005_cell089.material}
        position={[0.23, -1.43, -0.18]}
        rotation={[-0.78, -0.3, -3.13]}
      />
      <mesh
        name="Plane005_cell091"
        geometry={nodes.Plane005_cell091.geometry}
        material={nodes.Plane005_cell091.material}
        position={[0.35, -1.73, 1.01]}
        rotation={[2.15, -0.94, -0.9]}
      />
      <mesh
        name="Plane005_cell107"
        geometry={nodes.Plane005_cell107.geometry}
        material={nodes.Plane005_cell107.material}
        position={[0.14, -2.91, 1.04]}
        rotation={[-2.96, -0.51, 2.12]}
      />
      <mesh
        name="Plane005_cell113"
        geometry={nodes.Plane005_cell113.geometry}
        material={nodes.Plane005_cell113.material}
        position={[-0.06, -1.43, -0.08]}
        rotation={[-0.81, -0.32, 1.37]}
      />
      <mesh
        name="Plane005_cell118"
        geometry={nodes.Plane005_cell118.geometry}
        material={nodes.Plane005_cell118.material}
        position={[0.08, -1.71, 0.73]}
        rotation={[-2.03, -0.22, -1.85]}
      />
      <mesh
        name="Plane005_cell139"
        geometry={nodes.Plane005_cell139.geometry}
        material={nodes.Plane005_cell139.material}
        position={[0.02, -3.18, 0.75]}
        rotation={[-0.31, 0.23, -1.12]}
      />
      <mesh
        name="Plane005_cell140"
        geometry={nodes.Plane005_cell140.geometry}
        material={nodes.Plane005_cell140.material}
        position={[-0.02, -3.37, 0.64]}
        rotation={[0.58, -1.02, 1.33]}
      />
      <mesh
        name="Plane005_cell142"
        geometry={nodes.Plane005_cell142.geometry}
        material={nodes.Plane005_cell142.material}
        position={[-0.21, -1.5, 0.68]}
        rotation={[0.55, -1.3, -1.25]}
      />
      <mesh
        name="Plane005_cell153"
        geometry={nodes.Plane005_cell153.geometry}
        material={nodes.Plane005_cell153.material}
        position={[-0.38, -2.74, 0.9]}
        rotation={[-0.27, -0.04, -2.26]}
      />
      <mesh
        name="Plane005_cell154"
        geometry={nodes.Plane005_cell154.geometry}
        material={nodes.Plane005_cell154.material}
        position={[-0.33, -2.93, 0.64]}
        rotation={[1.08, 0.34, 2.78]}
      />
      <mesh
        name="Plane005_cell157"
        geometry={nodes.Plane005_cell157.geometry}
        material={nodes.Plane005_cell157.material}
        position={[-0.24, -3.34, 0.74]}
        rotation={[1.73, -0.67, -1.09]}
      />
      <mesh
        name="Plane005_cell159"
        geometry={nodes.Plane005_cell159.geometry}
        material={nodes.Plane005_cell159.material}
        position={[-0.52, -1.44, 0.95]}
        rotation={[-2.19, 0.22, 2.99]}
      />
      <mesh
        name="Plane005_cell161"
        geometry={nodes.Plane005_cell161.geometry}
        material={nodes.Plane005_cell161.material}
        position={[-0.33, -1.84, 0.71]}
        rotation={[2.25, 0, -1.3]}
      />
      <mesh
        name="Plane005_cell166"
        geometry={nodes.Plane005_cell166.geometry}
        material={nodes.Plane005_cell166.material}
        position={[-0.6, -3.04, 0.71]}
        rotation={[1.95, 0.28, -0.89]}
      />
      <mesh
        name="Plane005_cell168"
        geometry={nodes.Plane005_cell168.geometry}
        material={nodes.Plane005_cell168.material}
        position={[-0.79, -1.54, 0.82]}
        rotation={[-2.57, -0.31, 2.56]}
      />
      <mesh
        name="Plane005_cell170"
        geometry={nodes.Plane005_cell170.geometry}
        material={nodes.Plane005_cell170.material}
        position={[-0.64, -1.83, 0.71]}
        rotation={[-2.68, -0.31, -2.44]}
      />
      <mesh
        name="Plane005_cell175"
        geometry={nodes.Plane005_cell175.geometry}
        material={nodes.Plane005_cell175.material}
        position={[-0.68, -2.64, 0.61]}
        rotation={[0.59, -0.93, -2.44]}
      />
      <mesh
        name="Plane005_cell176"
        geometry={nodes.Plane005_cell176.geometry}
        material={nodes.Plane005_cell176.material}
        position={[-0.65, -2.85, 1.08]}
        rotation={[1.98, 0.99, -0.42]}
      />
      <mesh
        name="Plane005_cell178"
        geometry={nodes.Plane005_cell178.geometry}
        material={nodes.Plane005_cell178.material}
        position={[-0.93, -3.1, 0.67]}
        rotation={[1.37, 0.44, 2.34]}
      />
      <mesh
        name="Plane005_cell181"
        geometry={nodes.Plane005_cell181.geometry}
        material={nodes.Plane005_cell181.material}
        position={[-1.02, -1.85, 0.72]}
        rotation={[2.86, 1.45, 1.21]}
      />
      <mesh
        name="Plane005_cell182"
        geometry={nodes.Plane005_cell182.geometry}
        material={nodes.Plane005_cell182.material}
        position={[-0.91, -2.52, 0.76]}
        rotation={[0.92, 0.54, 1.62]}
      />
      <mesh
        name="Plane005_cell183"
        geometry={nodes.Plane005_cell183.geometry}
        material={nodes.Plane005_cell183.material}
        position={[-1.06, -2.87, 0.68]}
        rotation={[-0.48, 0.8, -3.01]}
      />
      <mesh
        name="Plane005_cell185"
        geometry={nodes.Plane005_cell185.geometry}
        material={nodes.Plane005_cell185.material}
        position={[0.21, -1.85, 0.76]}
        rotation={[2.94, 0.56, -1.22]}
      />
      <mesh
        name="Planejumbo_cell188"
        geometry={nodes.Planejumbo_cell188.geometry}
        material={nodes.Planejumbo_cell188.material}
        position={[-1.62, -0.17, 0.8]}
        rotation={[-2.46, 0.5, 0.34]}
        scale={[2.7, 2.7, 2.7]}
      />
      <mesh
        name="Planejumbo_cell732"
        geometry={nodes.Planejumbo_cell732.geometry}
        material={nodes.Planejumbo_cell732.material}
        position={[0.08, -0.46, 0.48]}
        rotation={[-2.19, -0.8, 2]}
        scale={[2.1, 2.1, 2.1]}
      />
    </group>
  )
}

useGLTF.preload('/LandingModel.gltf')
